version: "3.9"
services:
  nextjs:
    user: nextjs
    env_file:
      - "./.env.local"
    image: nextjs:latest
    container_name: nextjs
    ports:
      - "3000:3000"
    restart: always
    network_mode: host
#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - /etc/ssl:/etc/nginx/ssl:ro
#    restart: always