#https://stackoverflow.com/questions/74185594/how-to-deploy-a-next-js-app-on-https-ssl-connection-with-docker
version: "3.9"
services:
  nextjs:
    user: nextjs
    env_file:
      - "./.env.local"
    image: nextjs:latest
    container_name: nextjs
    ports:
      - "3000:3000"
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nextjs
    volumes:
      - /etc/ssl:/etc/nginx/ssl:ro
    restart: always