name: cloudflare
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run --token TOKEN_HERE
    networks:
      - tunnel
    restart: unless-stopped
networks:
  tunnel: