import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import {dir} from 'i18next'
import {SessionProvider} from "@/components/SessionContext";
import {validateRequest} from "@/app/login/validateRequest";

const languages: string[] = ['en', 'de'];

interface StaticParams {
    lng: string;
}

export async function generateStaticParams(): Promise<StaticParams[]> {
    return languages.map((lng: string) => ({lng}));
}

interface RootLayoutProps {
    children: React.ReactNode;
    params: {
        lang: string;
    };
}

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({children, params: {lang}}: RootLayoutProps) {
    const session = await validateRequest();

    return (
        <html lang={lang} dir={dir(lang)}>
        <SessionProvider session={session}>
            <body className={`${inter.className} bgImg`}>
            <NavBar lang={lang}/>
            {children}
            </body>
        </SessionProvider>
        </html>
    );
}
